@startuml

component "api-gateway" as gate

node geoserver as gs {
  component plugin as plug
}

component "geo.so.ch/docs" as docs
component "files.geo.so.ch" as geo
component "geo.so.ch/documents" as rep

gate -- plug
plug -- docs
plug -- geo
plug -- rep

@enduml